stages:
  - docker

build-challenge:
  stage: docker
  image:
    name: $CI_REGISTRY/general/docker-images/docker-builder:latest
  variables:
    NO_CACHE:   "true"
    WORKDIR:    challenge
    NAME:       problemsmounting
    DOCKERFILE: Dockerfile
    TAGS:       challenge
  script:
    - /build.sh

build-solver:
  stage: docker
  image:
    name: $CI_REGISTRY/general/docker-images/docker-builder:latest
  variables:
    NO_CACHE:   "true"
    WORKDIR:    solver
    NAME:       problemsmounting
    DOCKERFILE: Dockerfile
    TAGS:       solver
  script:
    - /build.sh
