stages:
  - docker

variables:
  CHALLENGE_NAME: errcorr

build-challenge:
  stage: docker
  image:
    name: $CI_REGISTRY/general/docker-images/docker-builder:latest
  variables:
    NO_CACHE:   "true"
    WORKDIR:    generator
    NAME:       $CHALLENGE_NAME
    DOCKERFILE: Dockerfile
    TAGS:       generator
  script:
    - /build.sh

build-solver:
  stage: docker
  image:
    name: $CI_REGISTRY/general/docker-images/docker-builder:latest
  variables:
    NO_CACHE:   "true"
    WORKDIR:    solver
    NAME:       $CHALLENGE_NAME
    DOCKERFILE: Dockerfile
    TAGS:       solver
  script:
    - /build.sh
